version: 2.1

jobs:
  test-py27:
    docker:
    - image: cimg/python:2.7
    environment:
      PYTHON_VERSION: "2.7"
    working_directory: ~/repo
    steps: &test-steps
    # https://devops.stackexchange.com/questions/9147/how-to-get-other-than-no-value-when-interpolating-environment-some-var/9177
    - run: echo "${PYTHON_VERSION}" > /tmp/python_version
    - checkout
    - restore_cache:
        keys:
        - test-v1-{{ checksum "/tmp/python_version" }}-{{ checksum "pyproject.toml" }}-
        - test-v1-{{ checksum "/tmp/python_version" }}-
    - run:
        name: Install dependencies
        command: |
          if [ "${PYTHON_VERSION}" = "2.7" ]; then
            python -mvirtualenv venv
          else
            python -mvenv venv
          fi
          . venv/bin/activate
          poetry install
          poetry update
    - save_cache:
        key: test-v1-{{ checksum "/tmp/python_version" }}-{{ checksum "pyproject.toml" }}-{{ epoch }}
        paths:
        - ./venv
    - run:
        name: Test
        command: |
          . venv/bin/activate
          pytest -vv --junitxml=/tmp/test-results/pytest/unittest.xml
    - store_test_results:
        path: /tmp/test-results

  test-py35:
    docker:
    - image: cimg/python:3.5
    environment:
      PYTHON_VERSION: "3.5"
    working_directory: ~/repo
    steps: *test-steps

  test-py36:
    docker:
    - image: cimg/python:3.6
    environment:
      PYTHON_VERSION: "3.6"
    working_directory: ~/repo
    steps: *test-steps

  test-py37:
    docker:
    - image: cimg/python:3.7
    environment:
      PYTHON_VERSION: "3.7"
    working_directory: ~/repo
    steps: *test-steps

  test-py38:
    docker:
    - image: cimg/python:3.8
    environment:
      PYTHON_VERSION: "3.8"
    working_directory: ~/repo
    steps: *test-steps

  test-py39:
    docker:
    - image: cimg/python:3.9
    environment:
      PYTHON_VERSION: "3.9"
    working_directory: ~/repo
    steps: *test-steps

workflows:
  version: 2
  test:
    jobs:
    - test-py27
    - test-py35
    - test-py36
    - test-py37
    - test-py38
    - test-py39
